Documentation:
  Enabled: false

TrailingComma:
  EnforcedStyleForMultiline: comma

AccessModifierIndentation:
  EnforcedStyle: outdent

MethodLength:
  Max: 15

CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    find: 'detect'
    find_all: 'select'
